apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "todo-app-chart.fullname" . }}-config
  labels:
    {{- include "todo-app-chart.labels" . | nindent 4 }}
data:
  API_BASE_URL: {{ .Values.global.apiBaseUrl | quote }}
  ENVIRONMENT_NAME: {{ .Values.global.environmentName | quote }}