apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "todo-app-chart.fullname" . }}-frontend
  labels:
    {{- include "todo-app-chart.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.frontend.replicaCount }}
  selector:
    matchLabels:
      {{- include "todo-app-chart.selectorLabels" . | nindent 6 }}
      app: todo-frontend
  template:
    metadata:
      labels:
        {{- include "todo-app-chart.selectorLabels" . | nindent 8 }}
        app: todo-frontend
    spec:
      containers:
      - name: {{ .Chart.Name }}-frontend
        image: "{{ .Values.frontend.image.repository }}:{{ .Values.frontend.image.tag }}"
        imagePullPolicy: {{ .Values.frontend.image.pullPolicy }}
        ports:
        - containerPort: 3000
        env:
        - name: REACT_APP_API_URL
          valueFrom:
            configMapKeyRef:
              name: {{ include "todo-app-chart.fullname" . }}-config
              key: API_BASE_URL
        resources:
          {{- toYaml .Values.resources | nindent 12 }}